### PR TITLE
fix: #227 concurrent modification error

### LINKED ISSUE #227: crash reporting: exception on `CrashReporting.send`
**Describe the bug**

Getting the following crash in the `CrashReporting.send` method.

**To Reproduce**

- TBD

**Expected behavior**

- Crash should not happen

**Screenshots**

- None

**Environment (please complete the following information where applicable):**

- Raygun v5.0.0

**Logs**

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.autohive.mobile, PID: 26719
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:64)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.write(ReflectiveTypeAdapterFactory.java:251)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:491)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.write(ReflectiveTypeAdapterFactory.java:251)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:491)
	at com.google.gson.Gson.toJson(Gson.java:943)
	at com.google.gson.Gson.toJson(Gson.java:898)
	at com.google.gson.Gson.toJson(Gson.java:847)
	at com.google.gson.Gson.toJson(Gson.java:824)
	at com.raygun.raygun4android.CrashReporting$send$1.invokeSuspend(CrashReporting.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(CrashReporting), StandaloneCoroutine{Cancelling}@1f76918, Dispatchers.IO]
```

**Possible Solution**

- TBD

### PR DESCRIPTION
**Pull request by miquelbeltran**
### Description :memo:

Fixes #227 

A concurrent modification was happening in the Breadcrumbs while the message serialization was running.

To avoid this issue, the following changes were made:

- Copy the list of breadcrumbs when building the Raygun message, rather than using the same list instance
- Copy as well the Tags and Custom Data payloads to avoid similar issues
- Ensure modifying breadcrumbs happens synchronously

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Updates**

See description

### Test plan :test_tube:

Tested with app currently in development

### Author to check :eyeglasses:
- [ ] Project and all contained modules build
- [ ] Tested on appropriate devices/emulators and SDK versions
- [ ] Reviewed by another developer
- [ ] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Change has been tested on a device/emulator
- [ ] Code is written to standards
- [ ] Appropriate tests have been written (code comments, internal docs)

### CODE REVIEW

File: provider/src/main/java/com/raygun/raygun4android/CrashReporting.kt [hunk 1]
```diff
@@ -48,14 +48,20 @@ object CrashReporting {
         recordBreadcrumb(breadcrumb)
     }
 
+    private val breadcrumbLock = Any()
```
Comment (velocitysystems) [inline provider/src/main/java/com/raygun/raygun4android/CrashReporting.kt]: Rather than a lock we could use `CopyOnWriteArrayList<RaygunBreadCrumbMessage>()`.
This is a thread-safe variant of `ArrayList<T>`.
- Reads are lock-free and always safe
- Writes just copy the list _internally_

**Review by velocitysystems — CHANGES_REQUESTED** [review]

File: provider/src/main/java/com/raygun/raygun4android/CrashReporting.kt (hunk 1 above)
Comment (TheRealAgentK) [reply provider/src/main/java/com/raygun/raygun4android/CrashReporting.kt]: I think both the `synchronized` block and the `CopyOnWriteArrayList` approach would work.

Using the COWAL seems a bit cleaner though.

**Review by velocitysystems — APPROVED** [review]

**Comment by miquelbeltran** [comment]
Did a couple of changes:
- Switched to `CopyOnWriteArrayList` as proposed
- Modified the `mergeList` and `mergeMap` methods so they always return a copy (not 100% related to this bug but should avoid future similar issues)

**Review by TheRealAgentK — APPROVED** [review]
